version: '3.4'
services:
    # mailhog:
    #     image: mailhog/mailhog
    #     logging:
    #         driver: 'none'
    #     ports:
    #         - 1025:1025
    #         - 8025:8025
    mysql:
        image: mysql:8.0
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123123
            MYSQL_DATABASE: Economic
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        links:
            - mysql
        environment:
            - PMA_ARBITRARY=1
    web:
        tty: true
        stdin_open: true
        command: bash
        build: ./docker
        links:
            - mysql
        ports:
            - 8088:8000
        environment:
            APP_DEBUG: 'true'
            XDEBUG_MODE: coverage
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin
        volumes:
            - .:/app:cached
            - ./storage:/app/storage/
            - ./docker-dev/web/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./docker/supervisor/:/etc/supervisor.d/
    # cron:
    #     build: ./docker/cron
    #     command: cron -f
    #     volumes:
    #         - .:/app:cached
volumes:
    composer_caches:
    mysql-data:
